from typing import Dict, List

# ______________________________________________________________________
COUNTRY_MAPPING: Dict[str, int] = {
    "Australia": 1,
    "Austria": 2,
    "Azerbaijan": 3,
    "Albania": 4,
    "Algeria": 5,
    "American_Samoa": 6,
    "Anguilla": 7,
    "Angola": 8,
    "Andorra": 9,
    "Antarctica": 10,
    "Antigua_and_Barbuda": 11,
    "Argentina": 12,
    "Armenia": 13,
    "Aruba": 14,
    "Afghanistan": 15,
    "Bahamas": 16,
    "Bangladesh": 17,
    "Barbados": 18,
    "Bahrain": 19,
    "Belarus": 20,
    "Belize": 21,
    "Belgium": 22,
    "Benin": 23,
    "Bermuda": 24,
    "Bulgaria": 25,
    "Bolivia": 26,
    "Bosnia_and_Herzegovina": 27,
    "Botswana": 28,
    "Brazil": 29,
    "British_Indian_Ocean_Territory": 30,
    "Brunei_Darussalam": 31,
    "Burkina_Faso": 32,
    "Burundi": 33,
    "Bhutane": 34,
    "Vanuatu": 35,
    "Hungary": 36,
    "Venezuela": 37,
    "Virgin_Islands_British": 38,
    "Virgin_Islands_USA": 39,
    "Vietnam": 40,
    "Gabon": 41,
    "Haiti": 42,
    "Guyana": 43,
    "Gambia": 44,
    "Ghana": 45,
    "Guadeloupe": 46,
    "Guatemala": 47,
    "Guinea": 48,
    "Guinea_Bissau": 49,
    "Germany": 50,
    "Guernsey": 51,
    "Gibraltar": 52,
    "Honduras": 53,
    "Hong_Kong": 54,
    "Grenada": 55,
    "Greenland": 56,
    "Greece": 57,
    "Georgia": 58,
    "Guam": 59,
    "Denmark": 60,
    "Jersey": 61,
    "Djibouti": 62,
    "Dominica": 63,
    "Dominican_Republic": 64,
    "Egypt": 65,
    "Zambia": 66,
    "West_Sahara": 67,
    "Zimbabwe": 68,
    "Israel": 69,
    "India": 70,
    "Indonesia": 71,
    "Jordan": 72,
    "Iraq": 73,
    "Iran_Islamic_Republic": 74,
    "Ireland": 75,
    "Iceland": 76,
    "Spain": 77,
    "Italy": 78,
    "Yemen": 79,
    "Cape_Verde": 80,
    "Kazakhstan": 81,
    "Cambodia": 82,
    "Cameroon": 83,
    "Canada": 84,
    "Qatar": 85,
    "Kenya": 86,
    "Cyprus": 87,
    "Kyrgyzstan": 88,
    "Kiribati": 89,
    "China": 90,
    "Cocos_Keeling_Islands": 91,
    "Colombia": 92,
    "Comoros": 93,
    "Congo": 94,
    "Congo_Democratic_Republic": 95,
    "Kosovo": 96,
    "Costa_Rica": 97,
    "Ivory_Coast": 98,
    "Cuba": 99,
    "Kuwait": 100,
    "Laos": 101,
    "Latvia": 102,
    "Lesotho": 103,
    "Lebanon": 104,
    "Libyan_Arab_Jamahiriya": 105,
    "Liberia": 106,
    "Liechtenstein": 107,
    "Lithuania": 108,
    "Luxembourg": 109,
    "Mauritius": 110,
    "Mauritania": 111,
    "Madagascar": 112,
    "Mayotte": 113,
    "Macau": 114,
    "Malawi": 115,
    "Malaysia": 116,
    "Mali": 117,
    "Pacific_Minor_Outlying_Islands_of_the_United_States": 118,
    "Maldives": 119,
    "Malta": 120,
    "Morocco": 121,
    "Martinique": 122,
    "Marshall_Islands": 123,
    "Mexico": 124,
    "Micronesia_Federated_States": 125,
    "Mozambique": 126,
    "Moldova_Republic": 127,
    "Monaco": 128,
    "Mongolia": 129,
    "Montserrat": 130,
    "Myanmar": 131,
    "Namibia": 132,
    "Nauru": 133,
    "Nepal": 134,
    "Niger": 135,
    "Nigeria": 136,
    "Netherlands_Antilles": 137,
    "Netherlands": 138,
    "Nicaragua": 139,
    "Niue": 140,
    "New_Zealand": 141,
    "New_Caledonia": 142,
    "Norway": 143,
    "United_Arab_Emirates": 144,
    "Oman": 145,
    "Bouvet_Island": 146,
    "Clipperton_Island": 147,
    "Isle_Of_Man": 148,
    "Norfolk_Island": 149,
    "Christmas_Island": 150,
    "Saint_Martins_Island": 151,
    "Heard_Island_and_McDonald_Islands": 152,
    "Cayman_Islands": 153,
    "Cook_Islands": 154,
    "Turks_and_Caicos_Islands": 155,
    "Pakistan": 156,
    "Palau": 157,
    "Palestinian_Territory_Occupied": 158,
    "Panama": 159,
    "Pontifical_See_State_Vatican_city": 160,
    "Papua_New_Guinea": 161,
    "Paraguay": 162,
    "Peru": 163,
    "Pitcairn": 164,
    "Poland": 165,
    "Portugal": 166,
    "Puerto_Rico": 167,
    "Republic_of_Macedonia": 168,
    "Reunion": 169,
    "Russia": 170,
    "Rwanda": 171,
    "Romania": 172,
    "Samoa": 173,
    "San_Marino": 174,
    "Sao_Tome_and_Principe": 175,
    "Saudi_Arabia": 176,
    "Swaziland": 177,
    "Saint_Elena": 178,
    "North_Korea": 179,
    "Northern_Mariana_Islands": 180,
    "Saint_Barthelemy": 181,
    "Saint_Pierre_and_Miquelon": 182,
    "Senegal": 183,
    "Saint_Vincent_and_the_Grenadines": 184,
    "Saint_Lucia": 185,
    "Saint_Kitts_and_Nevis": 186,
    "Serbia": 187,
    "Seychelles": 188,
    "Singapore": 189,
    "Syrian_Arab_Republic": 190,
    "Slovakia": 191,
    "Slovenia": 192,
    "United_Kingdom": 193,
    "United_States": 194,
    "Solomon_islands": 195,
    "Somalia": 196,
    "Sudan": 197,
    "Suriname": 198,
    "Sierra_Leone": 199,
    "Tajikistan": 200,
    "Thailand": 201,
    "Tanzania_United_Republic": 202,
    "Taiwan_China": 203,
    "Timor_Leste": 204,
    "Togo": 205,
    "Tokelau": 206,
    "Tonga": 207,
    "Trinidad_and_Tobago": 208,
    "Tuvalu": 209,
    "Tunisia": 210,
    "Turkmenistan": 211,
    "Turkey": 212,
    "Uganda": 213,
    "Uzbekistan": 214,
    "Ukraine": 215,
    "Wallis_and_Futuna": 216,
    "Uruguay": 217,
    "Faroe_islands": 218,
    "Fiji": 219,
    "Philippines": 220,
    "Finland": 221,
    "Falkland_Islands_Malvinas": 222,
    "France": 223,
    "French_Guiana": 224,
    "French_polynesia": 225,
    "French_Southern_Territories": 226,
    "Croatia": 227,
    "Central_African_Republic": 228,
    "Chad": 229,
    "Montenegro": 230,
    "Czech_Republic": 231,
    "Chile": 232,
    "Switzerland": 233,
    "Sweden": 234,
    "Svalbard_and_Jan_Mayen": 235,
    "Sri_Lanka": 236,
    "Ecuador": 237,
    "Equatorial_Guinea": 238,
    "Eland_Islands": 239,
    "El_Salvador": 240,
    "Eritrea": 241,
    "Estonia": 242,
    "Ethiopia": 243,
    "South_Africa": 244,
    "South_Georgia_and_the_South_Sandwich_Islands": 245,
    "South_Korea": 246,
    "Jamaica": 247,
    "Japan": 248,
}

COUNTRY_FOR_KEYS: List[int] = list(range(1, 249))

COUNTRY_MAPPING_RUSSIA: Dict[str, str] = {
    "Australia": "Австралия",
    "Austria": "Австрия",
    "Azerbaijan": "Азербайджан",
    "Albania": "Албания",
    "Algeria": "Алжир",
    "American_Samoa": "Американское Самоа",
    "Anguilla": "Ангилья",
    "Angola": "Ангола",
    "Andorra": "Андорра",
    "Antarctica": "Антарктида",
    "Antigua_and_Barbuda": "Антигуа и Барбуда",
    "Argentina": "Аргентина",
    "Armenia": "Армения",
    "Aruba": "Аруба",
    "Afghanistan": "Афганистан",
    "Bahamas": "Багамские Острова",
    "Bangladesh": "Бангладеш",
    "Barbados": "Барбадос",
    "Bahrain": "Бахрейн",
    "Belarus": "Беларусь",
    "Belize": "Белиз",
    "Belgium": "Бельгия",
    "Benin": "Бенин",
    "Bermuda": "Бермудские Острова",
    "Bulgaria": "Болгария",
    "Bolivia": "Боливия",
    "Bosnia_and_Herzegovina": "Босния и Герцеговина",
    "Botswana": "Ботсвана",
    "Brazil": "Бразилия",
    "British_Indian_Ocean_Territory": "Британская территория в Индийском океане",
    "Brunei_Darussalam": "Бруней",
    "Burkina_Faso": "Буркина Фасо",
    "Burundi": "Бурунди",
    "Bhutane": "Бутан",
    "Vanuatu": "Вануату",
    "Hungary": "Венгрия",
    "Venezuela": "Венесуэла",
    "Virgin_Islands_British": "Виргинские Острова (Великобритания)",
    "Virgin_Islands_USA": "Виргинские Острова (США)",
    "Vietnam": "Вьетнам",
    "Gabon": "Габон",
    "Haiti": "Гаити",
    "Guyana": "Гайана",
    "Gambia": "Гамбия",
    "Ghana": "Гана",
    "Guadeloupe": "Гваделупа",
    "Guatemala": "Гватемала",
    "Guinea": "Гвинея",
    "Guinea_Bissau": "Гвинея Бисау",
    "Germany": "Германия",
    "Guernsey": "Гернси",
    "Gibraltar": "Гибралтар",
    "Honduras": "Гондурас",
    "Hong_Kong": "Гонконг",
    "Grenada": "Гренада",
    "Greenland": "Гренландия",
    "Greece": "Греция",
    "Georgia": "Грузия",
    "Guam": "Гуам",
    "Denmark": "Дания",
    "Jersey": "Джерси",
    "Djibouti": "Джибути",
    "Dominica": "Доминика",
    "Dominican_Republic": "Доминиканская Республика",
    "Egypt": "Египет",
    "Zambia": "Замбия",
    "West_Sahara": "Западная Сахара",
    "Zimbabwe": "Зимбабве",
    "Israel": "Израиль",
    "India": "Индия",
    "Indonesia": "Индонезия",
    "Jordan": "Иордания",
    "Iraq": "Ирак",
    "Iran_Islamic_Republic": "Иран",
    "Ireland": "Ирландия",
    "Iceland": "Исландия",
    "Spain": "Испания",
    "Italy": "Италия",
    "Yemen": "Йемен",
    "Cape_Verde": "Кабо Верде",
    "Kazakhstan": "Казахстан",
    "Cambodia": "Камбоджа",
    "Cameroon": "Камерун",
    "Canada": "Канада",
    "Qatar": "Катар",
    "Kenya": "Кения",
    "Cyprus": "Кипр",
    "Kyrgyzstan": "Киргизия",
    "Kiribati": "Кирибати",
    "China": "Китай",
    "Cocos_Keeling_Islands": "Кокосовые Острова",
    "Colombia": "Колумбия",
    "Comoros": "Коморские Острова",
    "Congo": "Конго",
    "Congo_Democratic_Republic": "Демократическая Республика Конго",
    "Kosovo": "Косово",
    "Costa_Rica": "Коста Рика",
    "Ivory_Coast": "Кот д'Ивуар",
    "Cuba": "Куба",
    "Kuwait": "Кувейт",
    "Laos": "Лаос",
    "Latvia": "Латвия",
    "Lesotho": "Лесото",
    "Lebanon": "Ливан",
    "Libyan_Arab_Jamahiriya": "Ливия",
    "Liberia": "Либерия",
    "Liechtenstein": "Лихтенштейн",
    "Lithuania": "Литва",
    "Luxembourg": "Люксембург",
    "Mauritius": "Маврикий",
    "Mauritania": "Мавритания",
    "Madagascar": "Мадагаскар",
    "Mayotte": "Майотта",
    "Macau": "Макао",
    "Malawi": "Малави",
    "Malaysia": "Малайзия",
    "Mali": "Мали",
    "Pacific_Minor_Outlying_Islands_of_the_United_States": "Малые Тихоокеанские Острова США",
    "Maldives": "Мальдивы",
    "Malta": "Мальта",
    "Morocco": "Марокко",
    "Martinique": "Мартиника",
    "Marshall_Islands": "Маршалловы Острова",
    "Mexico": "Мексика",
    "Micronesia_Federated_States": "Микронезия",
    "Mozambique": "Мозамбик",
    "Moldova_Republic": "Молдова",
    "Monaco": "Монако",
    "Mongolia": "Монголия",
    "Montserrat": "Монтсеррат",
    "Myanmar": "Мьянма",
    "Namibia": "Намибия",
    "Nauru": "Науру",
    "Nepal": "Непал",
    "Niger": "Нигер",
    "Nigeria": "Нигерия",
    "Netherlands_Antilles": "Нидерландские Антильские Острова",
    "Netherlands": "Нидерланды",
    "Nicaragua": "Никарагуа",
    "Niue": "Ниуэ",
    "New_Zealand": "Новая Зеландия",
    "New_Caledonia": "Новая Каледония",
    "Norway": "Норвегия",
    "United_Arab_Emirates": "Объединенные Арабские Эмираты",
    "Oman": "Оман",
    "Bouvet_Island": "Остров Буве",
    "Clipperton_Island": "Остров Клиппертон",
    "Isle_Of_Man": "Остров Мэн",
    "Norfolk_Island": "Остров Норфолк",
    "Christmas_Island": "Остров Рождества",
    "Saint_Martins_Island": "Остров Святого Мартина",
    "Heard_Island_and_McDonald_Islands": "Острова Херд и Макдональд",
    "Cayman_Islands": "Острова Кайман",
    "Cook_Islands": "Острова Кука",
    "Turks_and_Caicos_Islands": "Острова Теркс и Кайкос",
    "Pakistan": "Пакистан",
    "Palau": "Палау",
    "Palestinian_Territory_Occupied": "Палестинские Территории",
    "Panama": "Панама",
    "Pontifical_See_State_Vatican_city": "Ватикан",
    "Papua_New_Guinea": "Папуа Новая Гвинея",
    "Paraguay": "Парагвай",
    "Peru": "Перу",
    "Pitcairn": "Питкэрн",
    "Poland": "Польша",
    "Portugal": "Португалия",
    "Puerto_Rico": "Пуэрто Рико",
    "Republic_of_Macedonia": "Северная Македония",
    "Reunion": "Реюньон",
    "Russia": "Россия",
    "Rwanda": "Руанда",
    "Romania": "Румыния",
    "Samoa": "Самоа",
    "San_Marino": "Сан Марино",
    "Sao_Tome_and_Principe": "Сан Томе и Принсипи",
    "Saudi_Arabia": "Саудовская Аравия",
    "Swaziland": "Свазиленд",
    "Saint_Elena": "Остров Святой Елены",
    "North_Korea": "Северная Корея",
    "Northern_Mariana_Islands": "Северные Марианские Острова",
    "Saint_Barthelemy": "Сен Бартелеми",
    "Saint_Pierre_and_Miquelon": "Сен Пьер и Микелон",
    "Senegal": "Сенегал",
    "Saint_Vincent_and_the_Grenadines": "Сент Винсент и Гренадины",
    "Saint_Lucia": "Сент Люсия",
    "Saint_Kitts_and_Nevis": "Сент Китс и Невис",
    "Serbia": "Сербия",
    "Seychelles": "Сейшелы",
    "Singapore": "Сингапур",
    "Syrian_Arab_Republic": "Сирия",
    "Slovakia": "Словакия",
    "Slovenia": "Словения",
    "United_Kingdom": "Великобритания",
    "United_States": "Соединенные Штаты",
    "Solomon_islands": "Соломоновы Острова",
    "Somalia": "Сомали",
    "Sudan": "Судан",
    "Suriname": "Суринам",
    "Sierra_Leone": "Сьерра Леоне",
    "Tajikistan": "Таджикистан",
    "Thailand": "Таиланд",
    "Tanzania_United_Republic": "Танзания",
    "Taiwan_China": "Тайвань",
    "Timor_Leste": "Тимор Лесте",
    "Togo": "Того",
    "Tokelau": "Токелау",
    "Tonga": "Тонга",
    "Trinidad_and_Tobago": "Тринидад и Тобаго",
    "Tuvalu": "Тувалу",
    "Tunisia": "Тунис",
    "Turkmenistan": "Туркменистан",
    "Turkey": "Турция",
    "Uganda": "Уганда",
    "Uzbekistan": "Узбекистан",
    "Ukraine": "Украина",
    "Wallis_and_Futuna": "Уоллис и Футуна",
    "Uruguay": "Уругвай",
    "Faroe_islands": "Фарерские Острова",
    "Fiji": "Фиджи",
    "Philippines": "Филиппины",
    "Finland": "Финляндия",
    "Falkland_Islands_Malvinas": "Фолклендские Острова",
    "France": "Франция",
    "French_Guiana": "Французская Гвиана",
    "French_polynesia": "Французская Полинезия",
    "French_Southern_Territories": "Французские Южные Территории",
    "Croatia": "Хорватия",
    "Central_African_Republic": "Центральноафриканская Республика",
    "Chad": "Чад",
    "Montenegro": "Черногория",
    "Czech_Republic": "Чехия",
    "Chile": "Чили",
    "Switzerland": "Швейцария",
    "Sweden": "Швеция",
    "Svalbard_and_Jan_Mayen": "Шпицберген и Ян Майен",
    "Sri_Lanka": "Шри Ланка",
    "Ecuador": "Эквадор",
    "Equatorial_Guinea": "Экваториальная Гвинея",
    "Eland_Islands": "Эландские Острова",
    "El_Salvador": "Сальвадор",
    "Eritrea": "Эритрея",
    "Estonia": "Эстония",
    "Ethiopia": "Эфиопия",
    "South_Africa": "Южная Африка",
    "South_Georgia_and_the_South_Sandwich_Islands": "Южная Георгия и Южные Сандвичевы Острова",
    "South_Korea": "Южная Корея",
    "Jamaica": "Ямайка",
    "Japan": "Япония",
}
# ______________________________________________________________________

# ______________________________________________________________________
CURRENCY_MAPPING: Dict[str, int] = {
    "AUD": 1,
    "EUR": 2,
    "AZN": 3,
    "ALL": 4,
    "DZD": 5,
    "USD": 6,
    "XCD": 7,
    "AOA": 8,
    "SYP": 9,
    "ARS": 10,
    "AMD": 11,
    "AWG": 12,
    "AFN": 13,
    "BSD": 14,
    "BDT": 15,
    "BBD": 16,
    "BHD": 17,
    "BYR": 18,
    "BZD": 19,
    "XOF": 20,
    "BMD": 21,
    "BGN": 22,
    "BOB": 23,
    "BOV": 24,
    "BAM": 25,
    "BWP": 26,
    "BRL": 27,
    "BND": 28,
    "BIF": 29,
    "BTN": 30,
    "INR": 31,
    "VUV": 32,
    "GBP": 33,
    "HUF": 34,
    "VEF": 35,
    "VND": 36,
    "GMD": 37,
    "XAF": 38,
    "HTG": 39,
    "GYD": 40,
    "GHS": 41,
    "GTQ": 42,
    "GNF": 43,
    "GIP": 44,
    "HNL": 45,
    "HKD": 46,
    "DKK": 47,
    "GEL": 48,
    "DJF": 49,
    "DOP": 50,
    "EGP": 51,
    "ZMW": 52,
    "MAD": 53,
    "ZWL": 54,
    "ILS": 55,
    "IDR": 56,
    "JOD": 57,
    "IQD": 58,
    "IRR": 59,
    "ISK": 60,
    "YER": 61,
    "CVE": 62,
    "KZT": 63,
    "KYD": 64,
    "KHR": 65,
    "CAD": 66,
    "QAR": 67,
    "KES": 68,
    "CNY": 69,
    "COP": 70,
    "COU": 71,
    "KMF": 72,
    "CDF": 73,
    "KPW": 74,
    "CRC": 75,
    "CUC": 76,
    "CUP": 77,
    "KWD": 78,
    "KGS": 79,
    "ANG": 80,
    "LAK": 81,
    "LSL": 82,
    "ZAR": 83,
    "LRD": 84,
    "LBP": 85,
    "LYD": 86,
    "CHF": 87,
    "MUR": 88,
    "MRO": 89,
    "MGA": 90,
    "MOP": 91,
    "MKD": 92,
    "MWK": 93,
    "MYR": 94,
    "FKP": 95,
    "MVR": 96,
    "XDR": 97,
    "MXN": 98,
    "MXV": 99,
    "MZN": 100,
    "MDL": 101,
    "MNT": 102,
    "MMK": 103,
    "NAD": 104,
    "NPR": 105,
    "NGN": 106,
    "NIO": 107,
    "NZD": 108,
    "XPF": 109,
    "NOK": 110,
    "AED": 111,
    "OMR": 112,
    "SHP": 113,
    "PKR": 114,
    "PAB": 115,
    "PGK": 116,
    "PYG": 117,
    "PEN": 118,
    "PLN": 119,
    "RUB": 120,
    "RWF": 121,
    "RON": 122,
    "SVC": 123,
    "WST": 124,
    "STD": 125,
    "SAR": 126,
    "SZL": 127,
    "SCR": 128,
    "RSD": 129,
    "SGD": 130,
    "XSU": 131,
    "SBD": 132,
    "SOS": 133,
    "XUA": 134,
    "SDG": 135,
    "SRD": 136,
    "SLL": 137,
    "TJS": 138,
    "THB": 139,
    "TWD": 140,
    "TZS": 141,
    "TOP": 142,
    "TTD": 143,
    "TND": 144,
    "TMT": 145,
    "TRY": 146,
    "UGX": 147,
    "UZS": 148,
    "UAH": 149,
    "UYI": 150,
    "UYU": 151,
    "FJD": 152,
    "PHP": 153,
    "HRK": 154,
    "CZK": 155,
    "CLF": 156,
    "CLP": 157,
    "CHE": 158,
    "CHW": 159,
    "SEK": 160,
    "LKR": 161,
    "ERN": 162,
    "ETB": 163,
    "KRW": 164,
    "SSP": 165,
    "JMD": 166,
    "JPY": 167,
    "BYN": 168,
}

CURRENCY_FOR_KEYS: List[int] = list(range(1, 169))
# ______________________________________________________________________

# ______________________________________________________________________
ORGANIZATIONAL_LEGAL_FORM_MAPPING: Dict[str, int] = {
    "Общество с ограниченной ответственностью": 1,
    "Акционерное общество": 2,
    "Индивидуальный предприниматель": 3,
    "Частное лицо": 4,
}

ORGANIZATIONAL_LEGAL_FORM_FOR_KEYS: List[int] = list(range(1, 5))
# ______________________________________________________________________

# ______________________________________________________________________
BANK_DETAIL_TYPE_MAPPING: Dict[str, int] = {
    "Отправитель": 1,
    "Получатель": 2,
    "Корреспондент": 3,
}

BANK_DETAIL_TYPE_FOR_KEYS: List[int] = list(range(1, 4))
# ______________________________________________________________________

# ______________________________________________________________________
ORDER_STATUS_MT_MAPPING: Dict[str, int] = {
    "Запрошен": 1,
    "Создан заказ": 2,
    "Заказ подтвержден": 3,
    "Выполнен": 4,
    "Отмена": 5,
}

ORDER_STATUS_MT_FOR_KEYS: List[int] = list(range(1, 7))
# ______________________________________________________________________

# ______________________________________________________________________
ROLE_UNDER_CONTRACT_MAPPING: Dict[str, int] = {
    "Подписант": 1,
    "Администратор контракта": 2,
    "Финансовый специалист": 3,
}

ROLE_UNDER_CONTRACT_FOR_KEYS: List[int] = list(range(1, 4))
# ______________________________________________________________________

# ______________________________________________________________________
BASIC_ACTION_SIGNATORY_MAPPING: Dict[str, int] = {
    "Устав": 1,
    "Доверенность": 2,
}

BASIC_ACTION_SIGNATORY_FOR_KEYS: List[int] = list(range(1, 3))
# ______________________________________________________________________
